version: 2.1

jobs:
  run_tests:
    docker:
      - image: python:3.6
      - image: postgres
        environment:
          POSTGRES_DB: "zosia"
          POSTGRES_USER: "zosia"
          POSTGRES_PASSWORD: "zosia"
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            pip3 install -r app/requirements.txt
            pip3 install flake8 coverage
      - run:
          name: Run run test with coverage check
          command: cd app/src && coverage run --source='.' --omit='*/migrations/*,zosia16/*,*/tests.py,*/__init__.py'  manage.py test --settings=zosia16.settings.test
      - run:
          name: Run syntax check
          command: flake8 --exclude=migrations --max-line-length=120 app/src || true
      - run:
          name: Show tests coverage report
          command: cd app/src && coverage report -m

  build_and_push_to_ecr:
    environment:
      AWS_ACCOUNT_ID: "463715963173"
      AWS_DEFAULT_REGION: "eu-central-1"
    docker:
      - image: docker:git
    steps:
      - run:
          name: Install awscli and docker-compose
          command: |
            apk add --no-cache python3
            pip3 install awscli
            pip3 install docker-compose~=1.23.0
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker images
          command: TAG="latest" docker-compose -f docker-compose.prod.yml build
      - run:
          name: Push image to ECR
          command: AWS_ACCESS_KEY_ID=${AWS_ACCESS_ID} AWS_SECRET_ACCESS_KEY=${AWS_ACCESS_SECRET_KEY} ./tools/upload_circle.sh

workflows:
  version: 2
  build:
    jobs:
      - run_tests
      - build_and_push_to_ecr:
          requires:
            - run_tests
          filters:
            branches:
              only: 
                - master
