# Generated by Django 2.2.4 on 2019-10-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.CharField(max_length=2048, verbose_name='Description')),
                ('duration', models.IntegerField(verbose_name='Duration')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('notes', models.CharField(blank=True, help_text='Your suggestions, requests and comments intended for organizers and a lot more,', max_length=800, null=True, verbose_name='Notes')),
                ('event_type', models.CharField(choices=[('1', 'Workshop'), ('2', 'Lecture'), ('3', 'Meal'), ('4', 'Other')], default='4', max_length=3, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='schedule.Schedule', verbose_name='Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('end', models.DateTimeField(verbose_name='End')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Event', verbose_name='Event')),
                ('schedule_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='schedule.ScheduleDay', verbose_name='Schedule day')),
            ],
        ),
    ]
